"""
report.py -- build a self-contained HTML mission report.

One click in the app produces a single .html file (Plotly JS embedded, so it
opens offline on any computer) that the team can attach to the final project
submission. Contains: mission stats, flight path, telemetry, and the
simulated layers with their honesty labels.
"""

import plotly.graph_objects as go

import ingest
import simulate

_CSS = """
<style>
 body {font-family: system-ui, sans-serif; max-width: 960px; margin: 2rem auto;
       padding: 0 1rem; color: #1c2530;}
 h1 {border-bottom: 3px solid #38bdf8; padding-bottom: .3rem;}
 .badge {display:inline-block; padding:2px 10px; border-radius:12px;
         font-size:.8rem; font-weight:600; color:#fff;}
 .measured {background:#16a34a;} .simulated {background:#ea580c;}
 table.stats {border-collapse: collapse; margin: 1rem 0;}
 table.stats td {border: 1px solid #cbd5e1; padding: 6px 14px;}
</style>
"""


def _fig_html(fig):
    """Embed a figure; include plotly.js only once (first figure)."""
    if not hasattr(_fig_html, "_js_done"):
        _fig_html._js_done = True
        return fig.to_html(full_html=False, include_plotlyjs=True)
    return fig.to_html(full_html=False, include_plotlyjs=False)


def build_report(df, dem, dem_label, thermal, mission_name="Survey mission"):
    """Return the full HTML report as a string."""
    if hasattr(_fig_html, "_js_done"):
        del _fig_html._js_done                      # reset between builds

    stats = ingest.mission_stats(df)
    bbox = simulate.flight_bbox(df)
    import numpy as np
    lat_axis = np.linspace(bbox[0], bbox[1], simulate.GRID)
    lon_axis = np.linspace(bbox[2], bbox[3], simulate.GRID)
    t_s = df["time_ms"] / 1000

    # figure 1: path over hillshade
    f1 = go.Figure()
    f1.add_trace(go.Heatmap(z=simulate.hillshade(dem), x=lon_axis, y=lat_axis,
                            colorscale="Greys", reversescale=True,
                            showscale=False))
    f1.add_trace(go.Scatter(x=df["lon"], y=df["lat"], mode="lines",
                            line=dict(color="deepskyblue", width=2),
                            name="flight path"))
    f1.update_layout(height=480, yaxis_scaleanchor="x",
                     title="Flight path over terrain relief")

    # figure 2: telemetry
    f2 = go.Figure()
    f2.add_trace(go.Scatter(x=t_s, y=df["alt_m"], name="altitude (m)"))
    f2.add_trace(go.Scatter(x=t_s, y=df["ground_speed_ms"], name="speed (m/s)"))
    f2.add_trace(go.Scatter(x=t_s, y=df["vbat_v"], name="battery (V)"))
    f2.update_layout(height=340, title="Telemetry over mission time (s)")

    # figure 3: thermal
    f3 = go.Figure()
    f3.add_trace(go.Heatmap(z=thermal, x=lon_axis, y=lat_axis,
                            colorscale="Inferno", colorbar=dict(title="°C")))
    f3.add_trace(go.Scatter(x=df["lon"], y=df["lat"], mode="lines",
                            line=dict(color="white", width=1.5),
                            name="flight path"))
    f3.update_layout(height=480, yaxis_scaleanchor="x",
                     title="Simulated thermal layer")

    rows = "".join(
        f"<tr><td>{k}</td><td>{v}</td></tr>" for k, v in [
            ("Duration", f"{stats['duration_s']:.0f} s"),
            ("Distance flown", f"{stats['distance_m']:.0f} m"),
            ("Max altitude", f"{stats['max_alt_m']:.1f} m"),
            ("Max ground speed", f"{stats['max_speed_ms']:.1f} m/s"),
            ("Minimum battery", f"{stats['min_vbat_v']:.2f} V"),
            ("Average satellites", f"{stats['avg_sats']:.0f}"),
            ("Terrain data source", dem_label),
        ])

    dem_badge = ("measured\">REAL DEM" if dem_label.startswith("real")
                 else "simulated\">SIMULATED")
    return f"""<!DOCTYPE html><html><head><meta charset="utf-8">
<title>{mission_name} — report</title>{_CSS}</head><body>
<h1>🛰️ {mission_name}</h1>
<p>Autonomous GPS survey drone — feasibility study report.
<span class="badge measured">MEASURED</span> flight telemetry with
<span class="badge simulated">SIMULATED</span> premium-sensor layers.</p>
<table class="stats">{rows}</table>
<h2>Flight path &amp; terrain <span class="badge {dem_badge}</span></h2>
{_fig_html(f1)}
<h2>Telemetry <span class="badge measured">MEASURED</span></h2>
{_fig_html(f2)}
<h2>Thermal layer <span class="badge simulated">SIMULATED</span></h2>
{_fig_html(f3)}
<p style="color:#64748b">Generated by the project dashboard. Simulated layers
are procedurally generated over the real flight's bounding box and are
clearly labeled; swapping in real sensors requires no pipeline changes.</p>
</body></html>"""
